### ISSUE TITLE
ssr storage folder

### ISSUE THREAD

**Issue by abstractFlo** [spatie/laravel-server-side-rendering-examples#1]
Hi, i have clone you repo for experimental use. But there is a problem. 

The `tmp_path` would not be set. Also the folder. Default they goes to `storage/app/ssr` but if this folder doesn't exist, the app is throwing an exception on production mode.

I hope you understand what i mean, my english is not the best :D

Kind regards

**Comment by sebastiandedeyne** [comment]
Yeah, this is needed for the `Node` driver, forgot to include it, my bad!
