### ISSUE TITLE
Parse error: syntax error, unexpected '='

### ISSUE THREAD

**Issue by lalitmee** [spatie/laravel-server-side-rendering-examples#2]
Hello, I am using react and laravel for server-side-rendering.
- Laravel Mix Version:- 1.0
- React Version:- 16.2.0
- PHP Version:- 7.0

- **What I did?**
`I clone your repo and then I tried to run it on my C9 workspace. I am also having another project of mine for the server-side-rendering. Both are shoiwing the same error on running.` 

- **Error**
```
/home/ubuntu/workspace/vendor/spatie/laravel-server-side-rendering/src/Resolvers/MixResolver.php
 
namespace Spatie\Ssr\Resolvers;
 
class MixResolver
{
    /** @var bool */
    protected $enabled;
 
    public function __construct(bool $enabled)
    {
        $this->enabled = $enabled;
    }
 
    public function __invoke(string $identifier) : string
    {
        if (! $this->enabled) {
            return $identifier;
        }
 
        [$publicPathWithoutQuery] = explode('?', $identifier);
 
        return public_path($publicPathWithoutQuery);
    }
}
 
Arguments
"Parse error: syntax error, unexpected '='"
Exception message: Parse error: syntax error, unexpected '='
```

```
ErrorException (E_ERROR)
Parse error: syntax error, unexpected '=' (View: /home/ubuntu/workspace/resources/views/vue.blade.php)
```

- Actually I am testing server-side-rending for SEO for my project but I am unable to test it. I took help from your repo but your repo is also coming up with this error. I appreciate your effort. I would be grateful to you if you can help me in this.

Thank you so much.

**Comment by sebastiandedeyne** [comment]
I just tagged a new version of `laravel-server-side-rendering`. It was using a PHP 7.1 feature, I restored PHP 7.0 compatibility.

**Comment by lalitmee** [comment]
Hey @sebastiandedeyne , I updated both projects. Still it is giving some different error. The error is same. 

- **Error**
```
Call to undefined method Spatie\Ssr\Renderer::withFallback()
```
```
ErrorException (E_ERROR)
Call to undefined method Spatie\Ssr\Renderer::withFallback() (View: /home/ubuntu/workspace/resources/views/react.blade.php)
```
If you can address me with this problem. It would be great. Thank You.

**Comment by sebastiandedeyne** [comment]
The react example wasn't up to date yet, only the Vue one. Should be ok now, let me know if somethings still missing :)

**Comment by lalitmee** [comment]
Thank you for doing that. Actually its working but on clicking **vue** link, it is showing the content of **vue's** page. On clicking **react** link, it is not showing anything. It is going to route **/react**, but nothing is visible. Since there are two links on the react's page in your example code. 

It is showing like the image below. 

![screenshot from 2018-03-09 21-52-22](https://user-images.githubusercontent.com/10762218/37217687-3484146e-23e4-11e8-8482-8d34aad66b90.png)
