### ISSUE TITLE
The command "node ..." failed

### ISSUE THREAD

**Issue by yuraplohov** [spatie/laravel-server-side-rendering-examples#7]
I launched a project and set in my .env
NODE_PATH=node
APP_ENV=production

But I have this error:

The command "node W:\OSPanel\domains\example\storage\app/ssr\342a336ef63a6e8f23f78828aec4b37a.js" failed. Exit Code: 1(General error) Working directory: W:\OSPanel\domains\example\public Output: ================ Error Output: ================ "node" �� ���� ����७��� ��� ���譥� ��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���. (View: W:\OSPanel\domains\example\resources\views\vue.blade.php)

Tell me please what can I do. Thank in advance

**Comment by khejit** [comment]
I have the same error. System: windows 10. I linked the domain using valet.
Without APP_ENV=production ssr is not used and there is no error, but when I want to check ssr I get this error with output that some js file can not be found. Directory storage/app/ssr contains only .gitignore.

**Comment by G-Bruin** [comment]
mac ,ProcessFailedException {#446 ▼
  -process: Process {#443 ▶}
  #message: """
    The command "/usr/local/bin/node /var/www/laravel-server/storage/app/ssr/3890b9877c241fc86a6a947db85d0f69.js" failed.\n
    \n
    Exit Code: 127(Command not found)\n
    \n
    Working directory: /var/www/laravel-server/public\n
    \n
    Output:\n
    ================\n
    \n
    \n
    Error Output:\n
    ================\n
    sh: /usr/local/bin/node: not found\n
    """
  #code: 0
  #file: "/var/www/laravel-server/vendor/symfony/process/Process.php"
  #line: 239
  trace: {▶}
}


Tell me please what can I do. Thank in advance

**Comment by d4rkr3pt0r** [comment]
same problem here:
The command "node C:\xampp\htdocs\storage\app/ssr\04113a0c6676e9396b9c85fba11a1bdd.js" failed. Exit Code: 1(General error) Working directory: C:\xampp\htdocs\public Output: ================ Error Output: ================ 'node' is not recognized as an internal or external command, operable program or batch file. (View: C:\xampp\htdocs\resources\views\vue.blade.php)

Nodejs is installed and working properly. environment variable is set.

**Comment by khejit** [comment]
@mdnpro : it's not the same error. Your says that node command hasn't been found, you have to provide full path to node or register node command so you can just use 'node' in your terminal anywhere.
We, on the other hand, had problem after node had been run. I eventually got it to work, but I didn't change anything. I just tried the same configuration on Mac, then reinstalled on Windows and everything worked. Very strange.

**Comment by d4rkr3pt0r** [comment]
@khejit I did all instructions but no luck.

Node path as environment variable.
NODE_PATH=node in .env file
APP_ENV=production in .env file
Still getting the same error. I'm using windows 10 x64.
I can use node in CMD and it's working fine.

**Comment by yuraplohov** [comment]
I transferred the same code to the server with centos and it works, but on windows 10 it does not work

**Comment by ohdoski** [comment]
Same error here. I think it maybe path problem in window. So i changed path like 

> C:\Program file\nodejs

 or

>  D\\:nodejs

, but neither work. I also try 

> D\\\\:nodejs

> node

> D:/nodejs

 but it`s same... anyone help?

**Comment by d4rkr3pt0r** [comment]
@ohdoski The reason of my problem was using `serve command` to run laravel. This way windows was unable to lock and terminate nodejs processes. But it works fine without using serve command.

**Comment by vintprox** [comment]
I don't understand why I have same issue. I use Laragon with PHP 7.2.17 + V8js extension enabled on Windows 10.
Made everything fine in configurations

```
...
APP_ENV=production
NODE_PATH=node
...
```

then I saw `{!! ssr('js/entry-server.js')->render() !!}` empty and breaking response, so eveything after it was not rendered. So I proceed in `ssr.php` configuration to disable `mix` resolver of path, and using path like this `{!! ssr(base_path().'/public/js/entry-server.js')->fallback('<div id="app">f</div>')->render() !!}` essentially provides me this error:

```
The command "node C:\proj\newsportal\storage\app/ssr\684c278c7f337480b7bd18d61d41ff85.js" failed.

Exit Code: 1(General error)

Working directory: C:\proj\newsportal\public

Output:
================


Error Output:
================
C:\proj\newsportal\storage\app\ssr\684c278c7f337480b7bd18d61d41ff85.js:2055
  if (next._normalized) {
           ^

TypeError: Cannot read property '_normalized' of undefined
    at normalizeLocation (C:\proj\newsportal\storage\app\ssr\684c278c7f337480b7bd18d61d41ff85.js:2055:12)
    at Object.match (C:\proj\newsportal\storage\app\ssr\684c278c7f337480b7bd18d61d41ff85.js:2125:20)
    at VueRouter.match (C:\proj\newsportal\storage\app\ssr\684c278c7f337480b7bd18d61d41ff85.js:3261:23)
    at AbstractHistory.transitionTo (C:\proj\newsportal\storage\app\ssr\684c278c7f337480b7bd18d61d41ff85.js:2649:27)
    at AbstractHistory.push (C:\proj\newsportal\storage\app\ssr\684c278c7f337480b7bd18d61d41ff85.js:3170:10)
    at VueRouter.push (C:\proj\newsportal\storage\app\ssr\684c278c7f337480b7bd18d61d41ff85.js:3341:16)
    at Module../resources/js/entry-server.js (C:\proj\newsportal\storage\app\ssr\684c278c7f337480b7bd18d61d41ff85.js:24572:54)
    at __webpack_require__ (C:\proj\newsportal\storage\app\ssr\684c278c7f337480b7bd18d61d41ff85.js:22:30)
    at Object.1 (C:\proj\newsportal\storage\app\ssr\684c278c7f337480b7bd18d61d41ff85.js:24615:18)
    at __webpack_require__ (C:\proj\newsportal\storage\app\ssr\684c278c7f337480b7bd18d61d41ff85.js:22:30)
 (View: C:\proj\newsportal\resources\views\layouts\app.blade.php) (View: C:\proj\newsportal\resources\views\layouts\app.blade.php)
```

I assume the path is correct, because when I misspell it fails with `Server script at path 'blahblah' doesn't exist.` Seems it has node run with correct one, but script fails on undefined `next`. I'm not able to debug it further since files are terminated.

Also I don't know why `public_path` helper is unaccessible when I put it in blade template. Maybe it's the cause?

I reverted  `ssr` configuration and my view:

```<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>blah</title>
    <script defer src="{{ asset('js/entry-client.js') }}"></script>
  </head>
  <body>
    {!! ssr('js/entry-server.js')->fallback('<div id="app"></div>')->render() !!}
  </body>
</html>
```

While `ssr(...)->fallback('<div id="app"></div>')` is
```
Renderer {#226 ▼
  #engine: Node {#225 ▶}
  #context: array:1 [▶]
  #env: array:2 [▶]
  #enabled: true
  #entry: "js/entry-server.js"
  #fallback: "<div id="app">f</div>"
  #debug: true
  #entryResolver: MixResolver {#222 ▶}
}
```

`ssr(...)->render()` returns just nothing and breaks response as I stated before.

**Comment by vintprox** [comment]
When I remove `$this->app->bind('path.public', function() { ... }` from `App\Providers\AppServiceProvider` I still get same error:

```
C:\proj\newsportal\storage\app\ssr\4593066437a128745c5ebda80bc0ec0f.js:2055
  if (next._normalized) {
           ^

TypeError: Cannot read property '_normalized' of undefined
```

Setting `'engine' => \Spatie\Ssr\Engines\V8::class` (instead of Node) in `ssr` configuration makes response break - returns nothing except the part before `{!! ssr(...)->render() !!}`.

I just don't understand.

**Comment by oziriemeka** [comment]
it took me almost 5 hours to figure this, and i think people who have figured it choose not to share a solution..

1. set ur NODE_PATH=node, and enable debug, 
2. Do not use PHP artisan serve, i don't know what way yo break the grammar but please not use it , use virtual Host instead.

**Comment by faizanmuzaffar12** [comment]
> it took me almost 5 hours to figure this, and i think people who have figured it choose not to share a solution..
> 
> 1. set ur NODE_PATH=node, and enable debug,
> 2. Do not use PHP artisan serve, i don't know what way yo break the grammar but please not use it , use virtual Host instead.

kindly tell how to use virtual host. ???

**Comment by aymanalhattami** [comment]
I couldn't solve the problem
I use invoiceninja version 5.0.17

**Comment by aymanalhattami** [comment]
This is the error message
The command "node ^"H:^\xampp^\htdocs^\invoiceninja5017-2^\vendor^\spatie^\browsershot^\src/../bin/browser.js^" ^"^{^\^"url^\^":^\^"file:^\/^\/C:^\^\Users^\^\AYMEN^\^\AppData^\^\Local^\^\Temp^\^\1471831584-0559500001601456126^\^\index.html^\^",^\^"action^\^":^\^"pdf^\^",^\^"options^\^":^{^\^"args^\^":^[^\^"--no-sandbox^\^"^],^\^"viewport^\^":^{^\^"width^\^":800,^\^"height^\^":600,^\^"deviceScaleFactor^\^":1^},^\^"displayHeaderFooter^\^":false,^\^"waitUntil^\^":^\^"networkidle0^\^",^\^"printBackground^\^":true^}^}^"" failed.

Exit Code: 1(General error)

Working directory: H:\xampp\htdocs\invoiceninja5017-2\public

Output:
================


Error Output:
================
'node' is not recognized as an internal or external command,
operable program or batch file.
(View: H:\xampp\htdocs\invoiceninja5017-2\resources\views\portal\ninja2020\invoices\show.blade.php)

**Comment by jbostoen** [comment]
Also still struggling with this.

I tried some debugging and if I try the command that is generated on the command line, it works.

But not from a default XAMPP installation running under the same user :|

**Comment by aybinv7** [comment]
after suffering with this the solution was actually using a virtual host , just like @shoutershub said , and i even used the php artisan serve command BUT YOU HAVE TO USE VIRTUAL HOST
and please : INSTALL puppeteer  because browsershot needs it under the hood.
so:
1- Use Virtual Host  (here is how u can do it  [https://www.scmgalaxy.com/tutorials/how-to-create-virtual-host-in-laravel/](url) )
2-Install  puppeteer 
` pnpm install puppeteer `


note: i think people who use laragon have virtual host by default
